buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0'
    }
}

subprojects {
    afterEvaluate {
        if (project.plugins.hasPlugin('com.android.application') ||
            project.plugins.hasPlugin('com.android.library')) {
            android {
                compileSdkVersion 36  // ← Forces ALL modules to SDK 36
                buildToolsVersion '34.0.0'
                defaultConfig {
                    minSdkVersion 24
                    targetSdkVersion 36
                }
            }
        }
    }
}